version: '2.4'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_MULTIPLE_DATABASES: pgapp,pgkc

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: flat

  keycloak:
    image: jboss/keycloak
    ports:
      - 8443:8443
      - 9990:9990
    mem_limit: 500m
    environment:
      KEYCLOAK_USER: kcuser
      KEYCLOAK_PASSWORD: kcpass
      KEYCLOAK_STATISTICS: db,http
      DB_ADDR: postgres
      DB_USER: pguser
      DB_PASSWORD: pgpass
      DB_DATABASE: pgkc
